[package]
name = "doctest_manifest"
version = "0.1.0"
edition = "2021"
authors = ["Tom Kunc <tom@tfpk.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dummy_file"
path = "src/main.rs"

[dependencies]
nom = "7.1.1"
